'use client';
import '../globals.css';
import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

const blank = { department:{name:''}, employee:{employeeCode:'',fullName:'',departmentId:'',role:'employee',pin:''}, job:{jobNumber:'',customerName:'',description:'',dueDate:'',priority:'3'}, material:{itemCode:'',description:'',unitOfMeasure:'ea',standardCost:''}, guidance:{scopeType:'role',role:'employee',departmentId:'',title:'',instructions:'',dailyGoal:''} };

export default function AdminPage(){
  const router=useRouter(); const [data,setData]=useState(null); const [forms,setForms]=useState(blank); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false); const [importing,setImporting]=useState(false);
  const load=useCallback(async()=>{const res=await fetch('/api/admin/setup',{cache:'no-store'}); if(res.status===401||res.status===403){router.push('/login');return;} const json=await res.json();if(!res.ok)setError(json.error);else setData(json);},[router]);
  useEffect(()=>{load();},[load]);
  function change(type,key,value){setForms(f=>({...f,[type]:{...f[type],[key]:value}}));}
  async function save(type,e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const res=await fetch('/api/admin/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,...forms[type]})});const json=await res.json();if(!res.ok)throw new Error(json.error);setForms(f=>({...f,[type]:blank[type]}));setNotice(`${type[0].toUpperCase()+type.slice(1)} saved.`);load();}catch(err){setError(err.message)}finally{setBusy(false)}}
  function csvValue(value){const text=String(value??'');return /[",\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
  function exportMaterials(){const rows=['item_code,description,unit_of_measure,standard_cost',...data.materials.map(m=>[m.item_code,m.description,m.unit_of_measure,m.standard_cost??''].map(csvValue).join(','))];const url=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='mastercraft-materials.csv';a.click();URL.revokeObjectURL(url);}
  function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c==='"'&&quoted&&next==='"'){cell+='"';i++;}else if(c==='"'){quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&next==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(rows.length<2)throw new Error('Your CSV needs a header row and at least one material.');const headers=rows.shift().map(x=>x.trim().toLowerCase().replaceAll(' ','_'));const value=(r,...names)=>r[headers.findIndex(h=>names.includes(h))]||'';return rows.map(r=>({itemCode:value(r,'item_code','itemcode','code'),description:value(r,'description','item_description'),unitOfMeasure:value(r,'unit_of_measure','uom','unit'),standardCost:value(r,'standard_cost','cost')}));}
  async function importMaterials(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;setImporting(true);setError('');setNotice('');try{if(!file.name.toLowerCase().endsWith('.csv'))throw new Error('Please choose a CSV file.');const materials=parseCsv(await file.text());const res=await fetch('/api/admin/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'materialsImport',materials})});const json=await res.json();if(!res.ok)throw new Error(json.error);setNotice(`${json.imported} material${json.imported===1?'':'s'} imported or updated.${json.skipped?.length?` Skipped invalid CSV rows: ${json.skipped.join(', ')}.`:''}`);load();}catch(err){setError(err.message)}finally{setImporting(false)}}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.push('/login');router.refresh();}
  if(!data)return <main className="shell"><div className="container"><div className="card">Loading administration...</div></div></main>;
  return <main className="shell"><div className="topbar"><a className="brand" href="/admin">MASTERCRAFT ADMIN</a><div className="navlinks"><a className="navlink" href="#guide">Guide</a><a className="navlink" href="#jobs">Jobs</a><a className="navlink" href="#materials">Materials</a><button className="toplink" onClick={logout}>Sign out</button></div></div><div className="container">
    <div className="card"><div className="kicker">Administration</div><h1>Shop setup</h1><p className="muted">Everything used to run the shop is managed here. Start with departments, then people, jobs, materials, and daily guidance.</p>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}</div>
    <section id="guide" className="card guide"><div><div className="kicker">First-time guide</div><h2>Where to find things</h2><p className="muted">Follow this order to set up the shop. Each item below takes you directly to its section.</p></div><div className="guide-links"><a href="#departments"><strong>1. Departments</strong><span>Create shop areas such as Fabrication or Shipping.</span></a><a href="#team"><strong>2. Team</strong><span>Add people, select their department and role, and set a PIN.</span></a><a href="#jobs"><strong>3. Jobs</strong><span>Create customer work orders before scheduling operations.</span></a><a href="#materials"><strong>4. Materials</strong><span>Add one item or import/export the whole list in a CSV file.</span></a><a href="#guidance"><strong>5. Daily guidance</strong><span>Set instructions and goals for a role or department.</span></a></div></section>
    <div className="grid two">
      <form id="team" className="card" onSubmit={e=>save('employee',e)}><div className="kicker">People</div><h2>Add employee</h2><div className="field"><label>Employee code</label><input value={forms.employee.employeeCode} onChange={e=>change('employee','employeeCode',e.target.value)} placeholder="E1002" /></div><div className="field"><label>Full name</label><input value={forms.employee.fullName} onChange={e=>change('employee','fullName',e.target.value)} /></div><div className="field"><label>Department</label><select value={forms.employee.departmentId} onChange={e=>change('employee','departmentId',e.target.value)}><option value="">No department</option>{data.departments.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><div className="grid two"><div className="field"><label>Role</label><select value={forms.employee.role} onChange={e=>change('employee','role',e.target.value)}><option value="employee">Employee</option><option value="supervisor">Supervisor</option><option value="admin">Admin</option></select></div><div className="field"><label>Initial PIN</label><input inputMode="numeric" type="password" value={forms.employee.pin} onChange={e=>change('employee','pin',e.target.value)} /></div></div><button disabled={busy} className="btn primary">ADD EMPLOYEE</button></form>
      <form id="departments" className="card" onSubmit={e=>save('department',e)}><div className="kicker">Organization</div><h2>Departments</h2><p className="muted">Create these first so employees and operations have a home.</p><div className="field"><label>Department name</label><input value={forms.department.name} onChange={e=>change('department','name',e.target.value)} placeholder="Welding" /></div><button disabled={busy} className="btn secondary">ADD DEPARTMENT</button><div className="simple-list">{data.departments.map(d=><span className="badge" key={d.id}>{d.name}</span>)}</div></form>
      <form id="jobs" className="card" onSubmit={e=>save('job',e)}><div className="kicker">Work</div><h2>Jobs</h2><p className="muted">Create a job here before assigning operations in the Supervisor board.</p><div className="field"><label>Job number</label><input value={forms.job.jobNumber} onChange={e=>change('job','jobNumber',e.target.value)} placeholder="MC-26052" /></div><div className="field"><label>Customer</label><input value={forms.job.customerName} onChange={e=>change('job','customerName',e.target.value)} /></div><div className="field"><label>Description</label><input value={forms.job.description} onChange={e=>change('job','description',e.target.value)} /></div><div className="grid two"><div className="field"><label>Due date</label><input type="date" value={forms.job.dueDate} onChange={e=>change('job','dueDate',e.target.value)} /></div><div className="field"><label>Priority</label><select value={forms.job.priority} onChange={e=>change('job','priority',e.target.value)}>{[1,2,3,4,5].map(p=><option key={p} value={p}>{p}</option>)}</select></div></div><button disabled={busy} className="btn primary">ADD JOB</button></form>
      <div id="materials" className="card"><div className="kicker">Inventory</div><h2>Materials</h2><p className="muted">Add one item below, or use CSV for your entire material list. Imported matching item codes are updated.</p><div className="bulk-actions"><button type="button" onClick={exportMaterials} className="btn secondary">EXPORT MATERIALS (CSV)</button><label className="btn primary file-button">{importing?'IMPORTING...':'IMPORT MATERIALS (CSV)'}<input disabled={importing} type="file" accept=".csv,text/csv" onChange={importMaterials}/></label></div><p className="hint">CSV columns: <code>item_code, description, unit_of_measure, standard_cost</code>.</p><form onSubmit={e=>save('material',e)}><div className="field"><label>Item code</label><input value={forms.material.itemCode} onChange={e=>change('material','itemCode',e.target.value)} /></div><div className="field"><label>Description</label><input value={forms.material.description} onChange={e=>change('material','description',e.target.value)} /></div><div className="grid two"><div className="field"><label>Unit of measure</label><input value={forms.material.unitOfMeasure} onChange={e=>change('material','unitOfMeasure',e.target.value)} /></div><div className="field"><label>Standard cost</label><input inputMode="decimal" value={forms.material.standardCost} onChange={e=>change('material','standardCost',e.target.value)} /></div></div><button disabled={busy} className="btn primary">ADD MATERIAL</button></form><div className="simple-list">{data.materials.slice(0,12).map(m=><span className="badge" key={m.id}>{m.item_code}</span>)}{data.materials.length>12&&<span className="muted">+ {data.materials.length-12} more</span>}</div></div>
      <form id="guidance" className="card" onSubmit={e=>save('guidance',e)}><div className="kicker">Daily expectations</div><h2>Instructions &amp; goals</h2><div className="field"><label>Apply to</label><select value={forms.guidance.scopeType} onChange={e=>change('guidance','scopeType',e.target.value)}><option value="role">Role</option><option value="department">Department</option></select></div>{forms.guidance.scopeType==='role'?<div className="field"><label>Role</label><select value={forms.guidance.role} onChange={e=>change('guidance','role',e.target.value)}><option value="employee">Employee</option><option value="supervisor">Supervisor</option><option value="admin">Admin</option></select></div>:<div className="field"><label>Department</label><select value={forms.guidance.departmentId} onChange={e=>change('guidance','departmentId',e.target.value)}><option value="">Select department</option>{data.departments.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div>}<div className="field"><label>Title</label><input value={forms.guidance.title} onChange={e=>change('guidance','title',e.target.value)} placeholder="Fabrication daily standard" /></div><div className="field"><label>Instructions</label><input value={forms.guidance.instructions} onChange={e=>change('guidance','instructions',e.target.value)} placeholder="Review work order before starting." /></div><div className="field"><label>Daily goal</label><input value={forms.guidance.dailyGoal} onChange={e=>change('guidance','dailyGoal',e.target.value)} placeholder="Complete assigned operations safely and accurately." /></div><button disabled={busy} className="btn secondary">SAVE GUIDANCE</button></form>
    </div>
    <div className="grid two"><div className="card"><div className="kicker">Current jobs</div><div className="table-wrap"><table className="table compact-table"><thead><tr><th>Job</th><th>Customer</th><th>Status</th></tr></thead><tbody>{data.jobs.length===0?<tr><td colSpan="3" className="muted">No jobs have been created yet.</td></tr>:data.jobs.map(j=><tr key={j.id}><td><strong>{j.job_number}</strong><br/><span className="muted">{j.description}</span></td><td>{j.customer_name||'—'}</td><td><span className="badge">{j.status.replaceAll('_',' ')}</span></td></tr>)}</tbody></table></div></div><div className="card"><div className="kicker">Current team</div><div className="table-wrap"><table className="table compact-table"><thead><tr><th>Code</th><th>Name</th><th>Department</th><th>Role</th></tr></thead><tbody>{data.employees.map(e=><tr key={e.id}><td>{e.employee_code}</td><td>{e.full_name}</td><td>{e.department_name||'—'}</td><td><span className="badge">{e.role}</span></td></tr>)}</tbody></table></div></div></div>
  </div></main>;
}
