'use client';
import '../globals.css';
import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

const blank = { department:{name:''}, employee:{employeeCode:'',fullName:'',departmentId:'',role:'employee',pin:''}, job:{jobNumber:'',customerName:'',description:'',dueDate:'',priority:'3'}, material:{itemCode:'',description:'',unitOfMeasure:'ea',standardCost:''}, guidance:{scopeType:'role',role:'employee',departmentId:'',title:'',instructions:'',dailyGoal:''} };

export default function AdminPage(){
  const router=useRouter(); const [data,setData]=useState(null); const [forms,setForms]=useState(blank); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{const res=await fetch('/api/admin/setup',{cache:'no-store'}); if(res.status===401||res.status===403){router.push('/login');return;} const json=await res.json();if(!res.ok)setError(json.error);else setData(json);},[router]);
  useEffect(()=>{load();},[load]);
  function change(type,key,value){setForms(f=>({...f,[type]:{...f[type],[key]:value}}));}
  async function save(type,e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const res=await fetch('/api/admin/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,...forms[type]})});const json=await res.json();if(!res.ok)throw new Error(json.error);setForms(f=>({...f,[type]:blank[type]}));setNotice(`${type[0].toUpperCase()+type.slice(1)} saved.`);load();}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.push('/login');router.refresh();}
  if(!data)return <main className="shell"><div className="container"><div className="card">Loading administration...</div></div></main>;
  return <main className="shell"><div className="topbar"><div className="brand">MASTERCRAFT ADMIN</div><div className="navlinks"><a className="navlink" href="/supervisor">Supervisor</a><button className="toplink" onClick={logout}>Sign out</button></div></div><div className="container">
    <div className="card"><div className="kicker">Administration</div><h1>Shop setup</h1><p className="muted">Create the core records used by the shop floor. New employees can sign in immediately.</p>{error&&<div className="alert error">{error}</div>}{notice&&<div className="alert success">{notice}</div>}</div>
    <div className="grid two">
      <form className="card" onSubmit={e=>save('employee',e)}><div className="kicker">People</div><h2>Add employee</h2><div className="field"><label>Employee code</label><input value={forms.employee.employeeCode} onChange={e=>change('employee','employeeCode',e.target.value)} placeholder="E1002" /></div><div className="field"><label>Full name</label><input value={forms.employee.fullName} onChange={e=>change('employee','fullName',e.target.value)} /></div><div className="field"><label>Department</label><select value={forms.employee.departmentId} onChange={e=>change('employee','departmentId',e.target.value)}><option value="">No department</option>{data.departments.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div><div className="grid two"><div className="field"><label>Role</label><select value={forms.employee.role} onChange={e=>change('employee','role',e.target.value)}><option value="employee">Employee</option><option value="supervisor">Supervisor</option><option value="admin">Admin</option></select></div><div className="field"><label>Initial PIN</label><input inputMode="numeric" type="password" value={forms.employee.pin} onChange={e=>change('employee','pin',e.target.value)} /></div></div><button disabled={busy} className="btn primary">ADD EMPLOYEE</button></form>
      <form className="card" onSubmit={e=>save('department',e)}><div className="kicker">Organization</div><h2>Add department</h2><div className="field"><label>Department name</label><input value={forms.department.name} onChange={e=>change('department','name',e.target.value)} placeholder="Welding" /></div><button disabled={busy} className="btn secondary">ADD DEPARTMENT</button><div className="simple-list">{data.departments.map(d=><span className="badge" key={d.id}>{d.name}</span>)}</div></form>
      <form className="card" onSubmit={e=>save('job',e)}><div className="kicker">Work</div><h2>Add job</h2><div className="field"><label>Job number</label><input value={forms.job.jobNumber} onChange={e=>change('job','jobNumber',e.target.value)} placeholder="MC-26052" /></div><div className="field"><label>Customer</label><input value={forms.job.customerName} onChange={e=>change('job','customerName',e.target.value)} /></div><div className="field"><label>Description</label><input value={forms.job.description} onChange={e=>change('job','description',e.target.value)} /></div><div className="grid two"><div className="field"><label>Due date</label><input type="date" value={forms.job.dueDate} onChange={e=>change('job','dueDate',e.target.value)} /></div><div className="field"><label>Priority</label><select value={forms.job.priority} onChange={e=>change('job','priority',e.target.value)}>{[1,2,3,4,5].map(p=><option key={p} value={p}>{p}</option>)}</select></div></div><button disabled={busy} className="btn primary">ADD JOB</button></form>
      <form className="card" onSubmit={e=>save('material',e)}><div className="kicker">Inventory</div><h2>Add material</h2><div className="field"><label>Item code</label><input value={forms.material.itemCode} onChange={e=>change('material','itemCode',e.target.value)} /></div><div className="field"><label>Description</label><input value={forms.material.description} onChange={e=>change('material','description',e.target.value)} /></div><div className="grid two"><div className="field"><label>Unit of measure</label><input value={forms.material.unitOfMeasure} onChange={e=>change('material','unitOfMeasure',e.target.value)} /></div><div className="field"><label>Standard cost</label><input inputMode="decimal" value={forms.material.standardCost} onChange={e=>change('material','standardCost',e.target.value)} /></div></div><button disabled={busy} className="btn primary">ADD MATERIAL</button></form>
      <form className="card" onSubmit={e=>save('guidance',e)}><div className="kicker">Daily expectations</div><h2>Instructions &amp; goals</h2><div className="field"><label>Apply to</label><select value={forms.guidance.scopeType} onChange={e=>change('guidance','scopeType',e.target.value)}><option value="role">Role</option><option value="department">Department</option></select></div>{forms.guidance.scopeType==='role'?<div className="field"><label>Role</label><select value={forms.guidance.role} onChange={e=>change('guidance','role',e.target.value)}><option value="employee">Employee</option><option value="supervisor">Supervisor</option><option value="admin">Admin</option></select></div>:<div className="field"><label>Department</label><select value={forms.guidance.departmentId} onChange={e=>change('guidance','departmentId',e.target.value)}><option value="">Select department</option>{data.departments.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div>}<div className="field"><label>Title</label><input value={forms.guidance.title} onChange={e=>change('guidance','title',e.target.value)} placeholder="Fabrication daily standard" /></div><div className="field"><label>Instructions</label><input value={forms.guidance.instructions} onChange={e=>change('guidance','instructions',e.target.value)} placeholder="Review work order before starting." /></div><div className="field"><label>Daily goal</label><input value={forms.guidance.dailyGoal} onChange={e=>change('guidance','dailyGoal',e.target.value)} placeholder="Complete assigned operations safely and accurately." /></div><button disabled={busy} className="btn secondary">SAVE GUIDANCE</button></form>
    </div>
    <div className="card"><div className="kicker">Current team</div><div className="table-wrap"><table className="table"><thead><tr><th>Code</th><th>Name</th><th>Department</th><th>Role</th></tr></thead><tbody>{data.employees.map(e=><tr key={e.id}><td>{e.employee_code}</td><td>{e.full_name}</td><td>{e.department_name||'—'}</td><td><span className="badge">{e.role}</span></td></tr>)}</tbody></table></div></div>
  </div></main>;
}
