'use client';
import '../globals.css';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function SupervisorPage(){
  const router=useRouter(); const [data,setData]=useState(null); const [error,setError]=useState(''); const [now,setNow]=useState(Date.now());
  const load=useCallback(async()=>{const res=await fetch('/api/supervisor/dashboard',{cache:'no-store'});if(res.status===401||res.status===403){router.push('/login');return;}const j=await res.json();if(!res.ok){setError(j.error);return;}setData(j);},[router]);
  useEffect(()=>{load();const r=setInterval(load,15000);return()=>clearInterval(r);},[load]); useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});router.push('/login');router.refresh();}
  async function assign(operationId,employeeId){if(!employeeId)return;const res=await fetch('/api/supervisor/assign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operationId,employeeId:Number(employeeId)})});const j=await res.json();if(!res.ok)setError(j.error);else load();}
  const jobsInProgress=useMemo(()=>new Set((data?.active||[]).map(x=>x.jobs?.job_number).filter(Boolean)).size,[data]);
  if(!data)return <main className="shell"><div className="container"><div className="card">Loading supervisor dashboard...</div></div></main>;
  return <main className="shell"><div className="topbar"><div className="brand">MASTERCRAFT SUPERVISOR</div><div className="navlinks"><a className="navlink" href="/employee">My Work</a><button className="toplink" onClick={logout}>Sign out</button></div></div><div className="container">
    {error&&<div className="alert error">{error}</div>}
    <div className="grid three"><div className="card metric"><div className="kicker">Working Now</div><div className="big">{data.active.length}</div><div className="muted">employees on active jobs</div></div><div className="card metric"><div className="kicker">Jobs In Progress</div><div className="big">{jobsInProgress}</div><div className="muted">across the shop</div></div><div className="card metric"><div className="kicker">Open Operations</div><div className="big">{data.operations.length}</div><div className="muted">queued or in progress</div></div></div>
    <div className="card"><div className="row"><div><div className="kicker">Live Floor</div><h2>Who is working on what?</h2></div><span className="badge active">Live</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Employee</th><th>Job</th><th>Operation</th><th>Department</th><th>Elapsed</th></tr></thead><tbody>{data.active.length===0?<tr><td colSpan="5" className="muted">No active timers.</td></tr>:data.active.map(r=>{const mins=Math.max(0,Math.floor((now-new Date(r.started_at).getTime())/60000));return <tr key={r.id}><td>{r.employees?.full_name}</td><td>{r.jobs?.job_number}</td><td>{r.operations?.operation_name}</td><td>{r.operations?.departments?.name}</td><td>{Math.floor(mins/60)}h {mins%60}m</td></tr>})}</tbody></table></div></div>
    <div className="card"><div className="kicker">Department Schedule</div><h2>Operations Board</h2><div className="table-wrap"><table className="table"><thead><tr><th>Job</th><th>Description</th><th>Department</th><th>Operation</th><th>Assigned</th><th>Est.</th><th>Status</th></tr></thead><tbody>{data.operations.map(o=><tr key={o.id}><td><strong>{o.jobs?.job_number}</strong></td><td>{o.jobs?.description}</td><td>{o.departments?.name}</td><td>{o.operation_name}</td><td><div className="assigned-list">{(o.assignments||[]).map(a=><span className="badge" key={a.id}>{a.employees?.full_name}</span>)}</div><select className="inline-select" defaultValue="" onChange={e=>assign(o.id,e.target.value)}><option value="">+ Assign</option>{data.employees.map(emp=><option key={emp.id} value={emp.id}>{emp.full_name}</option>)}</select></td><td>{o.estimated_hours||'—'}</td><td><span className={'badge '+(o.status==='in_progress'?'active':'queued')}>{String(o.status).replaceAll('_',' ')}</span></td></tr>)}</tbody></table></div></div>
  </div></main>
}
